name: grabkit_export
description: Debug report and sharing module for GrabKit.
version: 0.1.0
homepage: https://github.com/pandytconsulting/GrabKit
repository: https://github.com/pandytconsulting/GrabKit/tree/main/packages/grabkit_export
issue_tracker: https://github.com/pandytconsulting/GrabKit/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  grabkit: ^0.1.0
  grabkit_logs: ^0.1.0
  grabkit_network: ^0.1.0
  grabkit_realtime: ^0.1.0
  package_info_plus: ^8.0.2
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
